import Link from 'next/link';
import { ArrowDown, CalendarDays } from 'lucide-react';
import type { Metadata } from 'next';
import { SiteLayout } from '@/components/site-layout';
import { PageHero } from '@/components/page-hero';

export const metadata: Metadata = { title: 'Projects and Experience', description: 'Selected institutional experience across mission support, workforce development, training, language services, technology, and trade implementation.' };

const projects = [
  ['2019–2021', 'Government of the United States', 'Overseas mission support', 'U.S. Embassy Annex Support', 'Human resources, payroll management, and floor management for catering service.', ['Workforce', 'Administration', 'Hospitality operations']],
  ['2018–2019', 'GIZ', 'Training and capacity building', 'Multi-Province Soft-Skills Training', 'Training across multiple provinces, with catering support for more than 5,000 participants across assignments.', ['Training', 'Participant logistics', 'Service coordination']],
  ['2016–2018', 'AWDP / Creative Associates / USAID', 'Workforce development', 'Workforce Development', 'Training of trainers, project-management training, job placement, employer needs assessment, participant logistics, and catering support.', ['Workforce', 'Training', 'Employer engagement']],
  ['2017–2018', 'Tetra Tech ISLA / USAID', 'Language services', 'Mission-Based Translation Services', 'English, Dari, and Pashto translation supporting project documentation, stakeholder communication, and implementation requirements.', ['Translation', 'Documentation', 'Stakeholder access']],
  ['2018', 'Export Promotion Agency of Afghanistan', 'Trade strategy implementation', 'Advancing Afghan Trade', 'Project management and implementation support for an export-promotion strategy.', ['Trade', 'Market support', 'Implementation']],
  ['Multi-year', 'Etisalat and Huawei', 'Telecommunications', 'Human Resources and Administrative Support', 'Human resources, payroll, manpower, call-center, language-training, and administrative support under employment cooperation arrangements.', ['HR', 'Payroll', 'Operations']],
  ['Period not stated', 'DAI-ALBA', 'Public administration', 'Public Administration and Office-Management Training', 'Training in public policy, public administration, and office management.', ['Training', 'Public sector', 'Capacity building']],
] as const;

export default function ProjectsPage() {
  return <SiteLayout current="Projects"><main id="main">
    <PageHero current="Projects" eyebrow="Selected project experience" title={<>Built through<br />delivery.</>} description="PUL’s institutional portfolio spans overseas mission support, workforce development, professional training, language services, technology support, and trade implementation. Historical experience is shown with its delivery context and does not imply current client endorsement." image="/assets/images/platform-mission-v2.webp" imageAlt="Illustrative logistics and mission support operations"><div className="button-row"><a className="button" href="#experience">Explore experience<ArrowDown /></a><Link className="button button-ghost" href="/capability/">Capability Statement</Link></div></PageHero>
    <section className="section project-overview"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Experience at a glance</p><h2>Practical work across<br /><span>connected disciplines.</span></h2></div><p>The experience below is drawn from the approved 2026 Company Profile and Capability Statement.</p></div><div className="experience-pillars"><div><strong>Mission operations</strong><span>Staffing · facilities · vendors</span></div><div><strong>People and programs</strong><span>Training · workforce · placement</span></div><div><strong>Access and engagement</strong><span>Translation · interpretation · outreach</span></div><div><strong>Systems and markets</strong><span>Technology · procurement · trade</span></div></div></div></section>
    <section className="section experience-section" id="experience"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Selected institutional heritage</p><h2>Assignments where<br /><span>execution mattered.</span></h2></div><p>Selected work delivered through PUL Consulting Services and the PUL management team.</p></div><div className="project-list">{projects.map(([period, client, context, title, description, tags]) => <article key={title}><div className="project-period">{period}</div><div className="project-client">{client}<br /><span>{context}</span></div><div className="project-detail"><h3>{title}</h3><p>{description}</p><div className="project-tags">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div><p className="heritage-disclosure project-disclosure">Attribution note: this page summarizes selected historical assignments documented in PUL’s approved profile. It does not represent these assignments as direct contracts awarded to PUL Global Partners LLC, nor as endorsements by named organizations.</p></div></section>
    <section className="section project-capability"><div className="shell capability-panel"><div><p className="eyebrow light">More detail</p><h2>Review the 2026 Capability Statement.</h2><p>See the complete mission-fit matrix, core competencies, NAICS classifications, differentiators, and selected performance summary.</p></div><Link className="button button-light" href="/capability/">Open Capability Statement</Link></div></section>
    <section className="contact"><div className="shell contact-inner"><div><p className="eyebrow light">Build the next assignment</p><h2>Looking for an implementation partner?</h2></div><div><p>Bring your contract context, mission need, and desired delivery role to a focused discussion.</p><Link className="button button-light" href="/schedule/">Request a Strategy Call<CalendarDays /></Link></div></div></section>
  </main></SiteLayout>;
}
