import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, BriefcaseBusiness, GraduationCap, Cpu, Route, Check, Languages, MapPinCheck, ClipboardCheck as Clipboard, FileDown } from 'lucide-react';
import type { Metadata } from 'next';
import { SiteLayout } from '@/components/site-layout';
import { PageHero } from '@/components/page-hero';

export const metadata: Metadata = { title: 'Solutions', description: 'Explore PUL Global Partners capabilities across management consulting, capacity building, technology and AI, and trade, logistics, and mission support.' };

const platforms = [
  { id: 'management', eyebrow: 'Business management consulting', title: <>Management Consulting<br /><span>&amp; Advisory</span></>, intro: 'From strategy and organizational design to implementation control, PUL helps clients convert objectives into executable plans and measurable results.', icon: BriefcaseBusiness, image: 'platform-management-v2.webp', services: [['Program & Project Management', 'Project startup, work planning, PMO support, implementation management, reporting, closeout, and delivery coordination.'], ['Staffing, Recruitment & Workforce', 'Workforce planning, recruitment, payroll coordination, HR administration, performance support, and role-specific staffing.'], ['Government Contracting & Business Support', 'Opportunity support, proposal and grant assistance, registration guidance, government liaison, stakeholder coordination, and market research.'], ['Monitoring, Evaluation & Learning', 'Assessments, participant tracking, surveys, performance reporting, evidence management, and AI-assisted reporting with human review.']] },
  { id: 'capacity', eyebrow: 'Training and capacity building', title: <>Capacity Building<br /><span>&amp; Specialized Services</span></>, intro: 'Practical capability building for people, institutions, and programs, supported by language access and stakeholder engagement.', icon: GraduationCap, image: 'platform-capacity-v2.webp', services: [['Training & Professional Development', 'Project management, leadership, office management, employability, professional communication, soft skills, and train-the-trainer programs.'], ['AI Literacy & Staff Adoption', 'Responsible AI literacy, use-case mapping, adoption planning, human-review workflows, and practical productivity support.'], ['Translation & Interpretation', 'General translation, interpretation, transcription, editing, proofreading, and simultaneous interpretation based on mission requirements.'], ['Program Implementation & Engagement', 'Participant coordination, workshops, outreach, stakeholder facilitation, events, communications, and implementation reporting.']] },
  { id: 'technology', eyebrow: 'IT solutions', title: <>Technology<br /><span>&amp; Digital Solutions</span></>, intro: 'Reliable infrastructure, systems, equipment, AI enablement, and digital workflows connected to the operational mission.', icon: Cpu, image: 'platform-technology-v1.webp', services: [['IT Consulting & Managed Support', 'Assessments, budgeting, help desk support, system administration, operating support, technical coordination, and specialized staffing.'], ['Infrastructure, Networks & Security Coordination', 'Wired and wireless networking, cabling, connectivity, equipment configuration, installation, and partner-enabled security requirements.'], ['Cloud & Digital Transformation', 'Cloud architecture and migration support, business applications, email systems, software and web support, and workflow improvement.'], ['Data, Reporting & AI Implementation', 'Data reporting tools, knowledge management, AI readiness, responsible tool adoption, and technology-enabled operations.']] },
  { id: 'mission', eyebrow: 'Federal and mission support', title: <>Trade, Logistics<br /><span>&amp; Mission Support</span></>, intro: 'Reliable execution across suppliers, people, facilities, transportation, hospitality, equipment, and local coordination.', icon: Route, image: 'platform-mission-v2.webp', services: [['Mission & Administrative Support', 'Local staffing, office support, facilities coordination, vendor management, transportation, lodging, and daily operational support.'], ['Procurement & Logistics', 'Procurement tracking, equipment and supplies, warehousing coordination, transportation, furniture, fixtures, and general goods.'], ['Trade & Sourcing', 'Supplier identification, market-linkage support, Made-in-USA export promotion, goods sourcing, purchasing, and local market intelligence.'], ['Events, Catering & Hospitality', 'Venue support, halal food service, workshop meals, registration, participant movement, vendor coordination, and service-quality monitoring.']] },
] as const;

export default function SolutionsPage() {
  return <SiteLayout current="Solutions"><main id="main">
    <PageHero current="Solutions" eyebrow="Solutions and capabilities" title={<>Practical expertise.<br />Integrated execution.</>} description="PUL helps clients move from objectives to implementation through four connected business platforms. Each platform can stand alone or work as part of a coordinated delivery model." image="/assets/images/platform-technology-v1.webp" imageAlt="Technology professionals reviewing an enterprise workflow"><div className="button-row"><a className="button" href="#platforms">Explore our solutions<ArrowDown /></a><Link className="button button-ghost" href="/contact/">Discuss a requirement</Link></div></PageHero>
    <section className="solutions-intro section"><div className="shell split-intro"><div><p className="eyebrow">Flexible solutions</p><h2>Support matched to<br /><span>the mission.</span></h2></div><div className="intro-copy"><p className="lead">Clients can engage PUL for a defined capability, integrate us with an internal team, or use us to coordinate an end-to-end implementation workstream.</p><div className="engagement-list"><div><strong>Implement independently</strong><p>Use a focused assessment, strategy, work plan, or implementation package.</p></div><div><strong>Collaborate with your team</strong><p>Add PUL capacity to an existing program, proposal, operating team, or technical initiative.</p></div><div><strong>Partner for full support</strong><p>Coordinate people, vendors, technology, logistics, reporting, and closeout through one delivery model.</p></div></div></div></div></section>
    <section className="section solution-overview" id="platforms"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Four connected platforms</p><h2>Capabilities that work<br /><span>together in the field.</span></h2></div><p>Explore the service view, then see how disciplines connect around mission needs.</p></div><div className="platform-showcase solution-showcase">{platforms.map((p) => <a key={p.id} className={`platform-link ${p.id === 'management' ? 'platform-warm' : p.id === 'capacity' ? 'platform-vibrant' : p.id === 'mission' ? 'platform-amber' : ''}`} href={`#${p.id}`}><Image src={`/assets/images/${p.image}`} alt={p.eyebrow} width={1122} height={1402} loading="lazy" /><span className="platform-shade" /><div><p>{p.eyebrow}</p><h3>{p.title}</h3><strong>Explore services<ArrowUpRight /></strong></div></a>)}</div></div></section>
    <section className="solution-platforms">{platforms.map(({ id, title, intro, icon: Icon, services }, i) => <article className={`solution-block ${i % 2 ? 'alternate' : ''}`} id={id} key={id}><div className="shell solution-grid"><div className="solution-title"><span>{String(i + 1).padStart(2, '0')}</span><Icon aria-hidden="true" /><p className="eyebrow">{['Business management consulting', 'Training and capacity building', 'IT solutions', 'Federal and mission support'][i]}</p><h2>{title}</h2><p>{intro}</p></div><div className="service-grid">{services.map(([name, text]) => <section key={name}><h3>{name}</h3><p>{text}</p></section>)}</div></div></article>)}</section>
    <section className="section solution-fit"><div className="shell"><div className="section-heading compact"><div><p className="eyebrow">How capabilities connect</p><h2>Designed around the problems<br /><span>missions actually face.</span></h2></div><p>Complex assignments require people, vendors, language access, technology, logistics, controls, and reporting to work together.</p></div><div className="fit-grid"><div><MapPinCheck /><h3>Local implementation</h3><p>Staffing, vendor coordination, facilities, transportation, and daily problem solving.</p></div><div><Languages /><h3>Stakeholder access</h3><p>Translation, interpretation, outreach, facilitation, and mission-facing communication.</p></div><div><Clipboard /><h3>Delivery control</h3><p>Work plans, acceptance criteria, reporting, issue escalation, records, and closeout.</p></div></div></div></section>
    <section className="section capability-cta"><div className="shell capability-panel"><div><p className="eyebrow light">Procurement ready</p><h2>Take the capability overview with you.</h2><p>Review core competencies, NAICS codes, buyer fit, differentiators, and selected institutional experience.</p></div><Link className="button button-light" href="/capability/"><FileDown />View capability statement</Link></div></section>
    <section className="contact"><div className="shell contact-inner"><div><p className="eyebrow light">Start with the requirement</p><h2>Let’s identify the right delivery model.</h2></div><div><p>Tell us the mission, operating environment, timeline, and capability need. We will recommend a focused first step.</p><Link className="button button-light" href="/contact/">Discuss a requirement<ArrowRight /></Link></div></div></section>
  </main></SiteLayout>;
}
